# Creates user-facing launchers for BYH:
#   1. Desktop shortcut  -> double-click to start
#   2. Project-root BYH.cmd -> double-click to start
# Idempotent: re-running overwrites both.
$ErrorActionPreference = 'Stop'

$root       = $PSScriptRoot
$exe        = Join-Path $root 'artifacts\publish\win-x64-nativeuia\BYH.exe'
$ico        = Join-Path $root 'src\SelectionAssistant.App\Assets\app-icon.ico'

if (-not (Test-Path $exe)) {
    throw "BYH exe not found. Publish first. Expected: $exe"
}

# --- 1. Desktop shortcut "BYH" ---
$desktop = [Environment]::GetFolderPath('Desktop')
$lnkPath = Join-Path $desktop 'BYH.lnk'
$ws = New-Object -ComObject WScript.Shell
$sc = $ws.CreateShortcut($lnkPath)
$sc.TargetPath        = $exe
$sc.WorkingDirectory  = Split-Path $exe -Parent
$sc.Description       = 'BYH - By Your Hand'
if (Test-Path $ico) { $sc.IconLocation = $ico }
$sc.Save()
Write-Output "Desktop shortcut : $lnkPath"

# --- 2. Project-root launcher (current ANSI codepage for Chinese path safety) ---
$cmdPath = Join-Path $root 'BYH.cmd'
$lines = @(
    '@echo off',
    'REM Auto-generated BYH launcher. Double-click to start BYH.',
    'start "" "%~dp0artifacts\publish\win-x64-nativeuia\BYH.exe"'
)
[System.IO.File]::WriteAllLines($cmdPath, $lines, [System.Text.Encoding]::Default)
Write-Output "Project launcher : $cmdPath"
Write-Output 'Done.'
